#!/system/bin/sh
#
# record the temp
#
#
top_dir=/data/ktests
tmp_dir=$top_dir/record/

#Source the PATH variable
#. $top_dir/.bashrc

#recorded temp Path
sys_cpufreq=/sys/devices/system/cpu/cpu0/cpufreq
current_cpufreq=$sys_cpufreq/scaling_cur_freq
cpu_online=/sys/devices/system/cpu/online
cpu_temp_m040=/sys/class/thermal/thermal_zone0/temp

sys_power=/sys/class/power_supply/fuelgauge
battery_temp=$sys_power/temp
battery_current=$sys_power/current_now
battery_voltage=$sys_power/voltage_now

mif_int=/sys/devices/system/cpu/busfreq/curr_freq
gpu_freq=/sys/module/mali/parameters/mali_gpu_clk


#check the path and file
#if [ ! -d $sys_cpufreq ]; then
#	echo "no $sys_cpufreq found,Test fail" && exit 1
#fi

#if [ ! -f $cpu_temp ]; then
#	echo "no $cpu_temp fount, Test fail " && exit 1

#fi

#if [ ! -d $sys_power ] ; then
#	echo "no $sys_power fount ,Test fail" && exit 1

#fi

# creat tmp dir
#[ ! -d $top_dir ] && mkdir $top_dir
#[ ! -d $tmp_dir ] && mkdir $tmp_dir
#[ -f $tmp_dir/recorddata.txt ] && rm $tmp_dir/recorddata.txt

# record the temp
echo "start record the temp"
#cd $tmp_dir


while :;
do
	cpufreq=`cat $current_cpufreq`
	cpuonline=`cat $cpu_online`
	cpuTemp=`cat $cpu_temp_m040`
	MifInt=`cat $mif_int`
	gpuFreq=`cat $gpu_freq`

	echo ">>> cpufreq: $cpufreq , MIF: $MifInt , cpuon: $cpuonline , cputemp: $cpuTemp , gpuFreq: $gpuFreq  <<<" 
#	echo "cpufreq: $cpufreq cpuon: $cpuonline cputemp: $cpuTemp battemp: $batteryTemp batcur: $batteryCurrent batvol: $batteryVoltage Mif_Int: $MifInt gpuFreq: $gpuFreq" >> recorddata.txt

	sleep 1
done

exit 1
